deployment:
  name: flask-deployment
  selectorApp: flask-pod
  replicaCount: 1
  image:
    name: flask-container
    repository: coder336/flask-blog-app
    tag: b1ed1504a5d44b94bab52c1d370de9fef2f141fa
  pullPolicy: IfNotPresent
  port: 5000
service:
  name: flask-service
  type: LoadBalancer
  protocol: TCP
  port: 8080
  targetPort: 5000
  selectorApp: flask-pod
