deployment:
  flask:
    replicaCount: 1
    image:
      repository: coder336/flask-blog-app
      tag: latest
service:
  flask-service:
    type: LoadBalancer
    protocol: TCP
    port: 8080
    targetPort: 5000
    selectorApp: flask-pod
