deployment:
  name: flask-deployment
  selectorApp: flask-pod
  replicaCount: 1
  image:
    name: flask-container
    repository: coder336/flask-blog-app
    tag: 8d08297cd15d67c8436cefc98acdb931a9e8e7f3
  pullPolicy: IfNotPresent
  port: 5000
service:
  name: flask-service
  type: LoadBalancer
  protocol: TCP
  port: 8080
  targetPort: 5000
  selectorApp: flask-pod
